[build]
  base    = "."
  command = "pnpm --filter @workspace/internship-expo run build:netlify"
  publish = "artifacts/internship-expo/dist"

[build.environment]
  NODE_VERSION  = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
